### ISSUE TITLE
Feat: Ability to connect and add documents to database

### ISSUE THREAD

**Issue by btellstrom** [btellstrom/DD2480_group_19_CI#10]
We need the ability to connect to the database and insert documents following the [schema](https://github.com/btellstrom/DD2480_group_19_CI/doc/mongo/build-schema.json).

**Comment by henrikglass** [comment]
Reopened: This doesn't seem to work correctly.

**Comment by btellstrom** [comment]
Are you sure that is the error? The error mentioned that we tried to index a list with a string, more specifically the `data` variable if I remember correctly, which would imply that the data would be delivered in the wrong format. I'll take a look again, but I'm fairly certain that was the case.

**Comment by btellstrom** [comment]
The error was not the above, but there are still errors.
